sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js: "8"
install:
  - npm install
  - npm run bootstrap
  - npm link scripts/babel-preset-folio-dev
  - npm link scripts/folio-test-helpers
after_success:
  - npm run cover
  - npm run report
branches:
  only: master
