sudo: false
node_js:
  - "8.11.1"
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
install:
  - yarn
  - yarn build
after_success:
  - yarn cover
  - yarn report
  - yarn gh-pages
branches:
  only: masterh
