version: 2
jobs:
  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: yarn
      - run: yarn build
      - run: yarn lint

  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn build

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn cover

workflows:
  version: 2
  do-all:
    jobs:
      - lint
      - build
      - test
