version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-
      - run:
          name: Install Dependencies
          command: yarn install --pure-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules

  lint:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: yarn lint

  test:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-
      - run: yarn install --pure-lockfile
      - run: yarn build
      - run: yarn test
      - run: yarn cover

workflows:
  version: 2
  build-lint-test:
    jobs:
      - build
      - lint
      - test
